/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 06 11:10:35 GMT 2021
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ElevatorSystem.Environment;
import java.util.List;
import main.PL_Interface_impl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PL_Interface_impl_ESTest extends PL_Interface_impl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      String[] stringArray0 = new String[3];
      stringArray0[0] = "5";
      stringArray0[1] = "no Exception";
      stringArray0[2] = "~K!2d8>P";
      pL_Interface_impl0.modifiedrandomSequenceOfActions(24);
      PL_Interface_impl.main(stringArray0);
      PL_Interface_impl.getIntegerMinMax(0, 0);
      pL_Interface_impl0.Specification3();
      pL_Interface_impl0.start(24, (-1));
      pL_Interface_impl0.modifiedrandomSequenceOfActions(24);
      pL_Interface_impl0.checkOnlySpecification((-1));
      PL_Interface_impl.listToString(pL_Interface_impl0.actionHistory);
      pL_Interface_impl0.Specification1();
      pL_Interface_impl0.isAbortedRun();
      pL_Interface_impl0.Specification13();
      pL_Interface_impl0.start(370, 24);
      PL_Interface_impl.getIntegerMinMax(0, 0);
      List<String> list0 = pL_Interface_impl0.getExecutedActions();
      PL_Interface_impl.actionHistory = list0;
      pL_Interface_impl0.isAbortedRun();
      pL_Interface_impl0.Specification14();
      pL_Interface_impl0.modifiedrandomSequenceOfActions(24);
      PL_Interface_impl.listToString(pL_Interface_impl0.actionHistory);
      pL_Interface_impl0.test(24, (-1));
      PL_Interface_impl.listToString(pL_Interface_impl0.actionHistory);
      PL_Interface_impl.listToString(PL_Interface_impl.actionHistory);
      pL_Interface_impl0.Specification3();
      // Undeclared exception!
      pL_Interface_impl0.Specification1();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      PL_Interface_impl.getBoolean();
      PL_Interface_impl.executedUnimplementedAction = true;
      // Undeclared exception!
      pL_Interface_impl0.modifiedrandomSequenceOfActions(195225787);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      pL_Interface_impl0.Specification1();
      Environment environment0 = new Environment(10);
      pL_Interface_impl0.env = environment0;
      pL_Interface_impl0.randomSequenceOfActions((-106));
      pL_Interface_impl0.isAbortedRun();
      pL_Interface_impl0.isAbortedRun();
      PL_Interface_impl.getIntegerMinMax(30, (-2236));
      List<String> list0 = pL_Interface_impl0.getExecutedActions();
      PL_Interface_impl.listToString(list0);
      PL_Interface_impl.listToString(pL_Interface_impl0.actionHistory);
      pL_Interface_impl0.Specification9();
      pL_Interface_impl0.Specification9();
      pL_Interface_impl0.modifiedrandomSequenceOfActions(100);
      pL_Interface_impl0.getExecutedActions();
      pL_Interface_impl0.randomSequenceOfActions(100);
      // Undeclared exception!
      pL_Interface_impl0.Specification3();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      pL_Interface_impl0.Specification13();
      pL_Interface_impl0.start(139, 139);
      pL_Interface_impl0.checkOnlySpecification(0);
      // Undeclared exception!
      pL_Interface_impl0.Specification2();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PL_Interface_impl.getBoolean();
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      pL_Interface_impl0.Specification3();
      pL_Interface_impl0.Specification3();
      pL_Interface_impl0.start(24, 24);
      pL_Interface_impl0.checkOnlySpecification(24);
      PL_Interface_impl.listToString(pL_Interface_impl0.actionHistory);
      pL_Interface_impl0.Specification9();
      pL_Interface_impl0.checkOnlySpecification(24);
      pL_Interface_impl0.randomSequenceOfActions(24);
      pL_Interface_impl0.Specification3();
      // Undeclared exception!
      pL_Interface_impl0.Specification14();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      PL_Interface_impl.actionHistory = pL_Interface_impl0.actionHistory;
      List<String> list0 = pL_Interface_impl0.getExecutedActions();
      pL_Interface_impl0.Specification1();
      pL_Interface_impl0.Specification13();
      pL_Interface_impl0.isAbortedRun();
      pL_Interface_impl0.test((-1), (-1));
      PL_Interface_impl.actionHistory = list0;
      PL_Interface_impl.executedUnimplementedAction = false;
      pL_Interface_impl0.Specification9();
      pL_Interface_impl0.Specification2();
      int int0 = 0;
      int int1 = 24;
      pL_Interface_impl0.start(0, 24);
      pL_Interface_impl0.Specification1();
      pL_Interface_impl0.getExecutedActions();
      int int2 = 716;
      pL_Interface_impl0.Specification3();
      PL_Interface_impl.getIntegerMinMax(716, 716);
      // Undeclared exception!
      pL_Interface_impl0.Specification9();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      PL_Interface_impl.getBoolean();
      int int0 = 0;
      pL_Interface_impl0.randomSequenceOfActions(0);
      int int1 = (-987);
      pL_Interface_impl0.test(5, (-987));
      pL_Interface_impl0.randomSequenceOfActions(0);
      int int2 = 1;
      pL_Interface_impl0.test((-987), 1);
      pL_Interface_impl0.Specification1();
      pL_Interface_impl0.checkOnlySpecification(574);
      String[] stringArray0 = new String[2];
      // Undeclared exception!
      pL_Interface_impl0.test(0, 574);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      pL_Interface_impl0.isAbortedRun();
      pL_Interface_impl0.Specification9();
      pL_Interface_impl0.Specification9();
      PL_Interface_impl.getBoolean();
      PL_Interface_impl.getBoolean();
      pL_Interface_impl0.modifiedrandomSequenceOfActions((-1034));
      PL_Interface_impl.executedUnimplementedAction = false;
      pL_Interface_impl0.Specification14();
      pL_Interface_impl0.randomSequenceOfActions(6);
      pL_Interface_impl0.test(6, 6);
      pL_Interface_impl0.Specification9();
      PL_Interface_impl.getBoolean();
      pL_Interface_impl0.Specification13();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      pL_Interface_impl0.Specification9();
      PL_Interface_impl.actionHistory = pL_Interface_impl0.actionHistory;
      pL_Interface_impl0.Specification9();
      pL_Interface_impl0.test((-246), (-246));
      pL_Interface_impl0.Specification3();
      pL_Interface_impl0.modifiedrandomSequenceOfActions(731);
      pL_Interface_impl0.checkOnlySpecification((-1));
      pL_Interface_impl0.Specification14();
      pL_Interface_impl0.Specification9();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(pL_Interface_impl0);
      
      Environment environment0 = null;
      pL_Interface_impl0.env = null;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification2();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.start(1638, 1638);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(pL_Interface_impl0);
      
      pL_Interface_impl0.checkOnlySpecification(0);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification1();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.start(0, 0);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification1();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      PL_Interface_impl.actionHistory = pL_Interface_impl0.actionHistory;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(1, PL_Interface_impl.actionHistory.size());
      assertFalse(PL_Interface_impl.actionHistory.isEmpty());
      
      pL_Interface_impl0.randomSequenceOfActions(6);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification9();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(pL_Interface_impl0);
      
      pL_Interface_impl0.Specification2();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification14();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification9();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      List<String> list0 = pL_Interface_impl0.getExecutedActions();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(0, list0.size());
      assertTrue(list0.isEmpty());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(list0);
      
      String string0 = PL_Interface_impl.listToString(list0);
      assertFalse(list0.contains(string0));
      assertEquals("", string0);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(0, list0.size());
      assertTrue(list0.isEmpty());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(pL_Interface_impl0);
      
      pL_Interface_impl0.randomSequenceOfActions((-2460));
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(pL_Interface_impl0);
      
      String[] stringArray0 = new String[0];
      PL_Interface_impl.main(stringArray0);
      assertEquals(0, stringArray0.length);
      
      pL_Interface_impl0.start(1868, 1868);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(pL_Interface_impl0);
      
      pL_Interface_impl0.start((-257), 1);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      String string0 = PL_Interface_impl.listToString(pL_Interface_impl0.actionHistory);
      assertEquals(" StartFromTop bobCall", string0);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(string0);
      
      pL_Interface_impl0.Specification9();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(pL_Interface_impl0);
      
      PL_Interface_impl.actionHistory = pL_Interface_impl0.actionHistory;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(0, PL_Interface_impl.actionHistory.size());
      assertTrue(PL_Interface_impl.actionHistory.isEmpty());
      
      PL_Interface_impl.executedUnimplementedAction = false;
      String string0 = PL_Interface_impl.listToString(pL_Interface_impl0.actionHistory);
      assertEquals("", string0);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(string0);
      
      pL_Interface_impl0.Specification1();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.start(0, 0);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification3();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.start(0, (-1));
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      List<String> list0 = PL_Interface_impl.actionHistory;
      assertEquals(0, list0.size());
      assertTrue(list0.isEmpty());
      assertNotNull(list0);
      
      String string0 = PL_Interface_impl.listToString(list0);
      assertFalse(list0.contains(string0));
      assertEquals("", string0);
      assertEquals(0, list0.size());
      assertTrue(list0.isEmpty());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(pL_Interface_impl0);
      
      String[] stringArray0 = new String[8];
      stringArray0[0] = "ElevatorSystem.Floor";
      stringArray0[1] = "";
      stringArray0[2] = "ElevatorSystem.Floor";
      stringArray0[3] = "";
      stringArray0[4] = "";
      stringArray0[5] = "";
      stringArray0[6] = "F;;wTH";
      stringArray0[7] = "_GlAs}DId~^Dfu>";
      PL_Interface_impl.main(stringArray0);
      assertEquals(8, stringArray0.length);
      
      // Undeclared exception!
      pL_Interface_impl0.randomSequenceOfActions(1505);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(pL_Interface_impl0);
      
      PL_Interface_impl.executedUnimplementedAction = false;
      pL_Interface_impl0.Specification13();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.checkOnlySpecification(827);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      Environment environment0 = pL_Interface_impl0.env;
      assertNotNull(environment0);
      
      pL_Interface_impl0.env = environment0;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification14();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.env = environment0;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = PL_Interface_impl.getBoolean();
      assertFalse(boolean0);
      
      boolean boolean1 = PL_Interface_impl.getBoolean();
      assertFalse(boolean1);
      assertTrue(boolean1 == boolean0);
      
      pL_Interface_impl0.Specification13();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification1();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      Random.setNextRandom(2);
      pL_Interface_impl0.Specification1();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification13();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.randomSequenceOfActions(2);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      // Undeclared exception!
      pL_Interface_impl0.randomSequenceOfActions(827);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(pL_Interface_impl0);
      
      pL_Interface_impl0.Specification9();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.start(24, 7);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.modifiedrandomSequenceOfActions(150);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      PL_Interface_impl.main((String[]) null);
      pL_Interface_impl0.randomSequenceOfActions((-3507));
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.modifiedrandomSequenceOfActions(424);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification14();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.checkOnlySpecification(226);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification13();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      boolean boolean0 = pL_Interface_impl0.isAbortedRun();
      assertFalse(boolean0);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      boolean boolean1 = pL_Interface_impl0.isAbortedRun();
      assertFalse(boolean1);
      assertTrue(boolean1 == boolean0);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification9();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.modifiedrandomSequenceOfActions((-464));
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification2();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification14();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      Environment environment0 = pL_Interface_impl0.env;
      assertNotNull(environment0);
      
      pL_Interface_impl0.env = environment0;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      List<String> list0 = pL_Interface_impl0.getExecutedActions();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(472, list0.size());
      assertFalse(list0.isEmpty());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(list0);
      
      pL_Interface_impl0.Specification9();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification9();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      Random.setNextRandom((-464));
      pL_Interface_impl0.Specification1();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      boolean boolean2 = pL_Interface_impl0.isAbortedRun();
      assertFalse(boolean2);
      assertTrue(boolean2 == boolean1);
      assertTrue(boolean2 == boolean0);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(pL_Interface_impl0);
      
      pL_Interface_impl0.env = null;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.start((-2041), (-2041));
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification14();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      boolean boolean0 = PL_Interface_impl.getBoolean();
      assertFalse(boolean0);
      
      PL_Interface_impl.executedUnimplementedAction = true;
      PL_Interface_impl.executedUnimplementedAction = false;
      String string0 = PL_Interface_impl.listToString(pL_Interface_impl0.actionHistory);
      assertEquals(" StartFromTop", string0);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(string0);
      
      boolean boolean1 = PL_Interface_impl.getBoolean();
      assertFalse(boolean1);
      assertTrue(boolean1 == boolean0);
      
      // Undeclared exception!
      pL_Interface_impl0.test((-2041), 781);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(pL_Interface_impl0);
      
      pL_Interface_impl0.test(3, 3);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      boolean boolean0 = pL_Interface_impl0.isAbortedRun();
      assertFalse(boolean0);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      //  // Unstable assertion: assertFalse(pL_Interface_impl0.isAbortedRun());
      //  // Unstable assertion: assertFalse(PL_Interface_impl.executedUnimplementedAction);
      //  // Unstable assertion: assertNotNull(pL_Interface_impl0);
      
      pL_Interface_impl0.Specification13();
      //  // Unstable assertion: assertFalse(pL_Interface_impl0.isAbortedRun());
      //  // Unstable assertion: assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification1();
      //  // Unstable assertion: assertFalse(pL_Interface_impl0.isAbortedRun());
      //  // Unstable assertion: assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      PL_Interface_impl.actionHistory = pL_Interface_impl0.actionHistory;
      //  // Unstable assertion: assertFalse(pL_Interface_impl0.isAbortedRun());
      //  // Unstable assertion: assertFalse(PL_Interface_impl.actionHistory.isEmpty());
      //  // Unstable assertion: assertEquals(2, PL_Interface_impl.actionHistory.size());
      
      boolean boolean0 = pL_Interface_impl0.isAbortedRun();
      //  // Unstable assertion: assertFalse(boolean0);
      //  // Unstable assertion: assertFalse(pL_Interface_impl0.isAbortedRun());
      //  // Unstable assertion: assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification13();
      //  // Unstable assertion: assertFalse(pL_Interface_impl0.isAbortedRun());
      //  // Unstable assertion: assertFalse(PL_Interface_impl.executedUnimplementedAction);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(pL_Interface_impl0);
      
      pL_Interface_impl0.Specification13();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification3();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification14();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(pL_Interface_impl0);
      
      pL_Interface_impl0.Specification3();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.modifiedrandomSequenceOfActions((-2218));
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification2();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      int int0 = PL_Interface_impl.getIntegerMinMax((-2989), 6);
      assertEquals((-2690), int0);
      
      pL_Interface_impl0.Specification13();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification3();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.modifiedrandomSequenceOfActions(0);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      int int1 = PL_Interface_impl.getIntegerMinMax(1913, 1549);
      assertEquals(1805, int1);
      assertFalse(int1 == int0);
      
      pL_Interface_impl0.Specification2();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification1();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification9();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      boolean boolean0 = PL_Interface_impl.getBoolean();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(pL_Interface_impl0);
      
      pL_Interface_impl0.Specification2();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      int int0 = PL_Interface_impl.getIntegerMinMax(0, 0);
      assertEquals(0, int0);
      
      pL_Interface_impl0.modifiedrandomSequenceOfActions(967);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.checkOnlySpecification(0);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      String[] stringArray0 = new String[1];
      stringArray0[0] = "(U%5HL|";
      PL_Interface_impl.main(stringArray0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(pL_Interface_impl0);
      
      pL_Interface_impl0.start((-1), (-1));
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.modifiedrandomSequenceOfActions((-1));
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.checkOnlySpecification((-1));
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification14();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      PL_Interface_impl.executedUnimplementedAction = false;
      int int0 = PL_Interface_impl.getIntegerMinMax((-1), (-1));
      assertEquals((-1), int0);
      
      pL_Interface_impl0.Specification3();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.checkOnlySpecification(1);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification9();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.test(1, (-1));
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification3();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.env = null;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification14();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      List<String> list0 = pL_Interface_impl0.getExecutedActions();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(list0.isEmpty());
      assertEquals(1, list0.size());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(list0);
      
      pL_Interface_impl0.Specification14();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      boolean boolean0 = PL_Interface_impl.getBoolean();
      assertFalse(boolean0);
      
      pL_Interface_impl0.checkOnlySpecification((-1));
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification9();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.randomSequenceOfActions((-2733));
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification13();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      PL_Interface_impl.main((String[]) null);
      boolean boolean1 = pL_Interface_impl0.isAbortedRun();
      assertFalse(boolean1);
      assertTrue(boolean1 == boolean0);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification1();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      int int1 = PL_Interface_impl.getIntegerMinMax((-1), (-1));
      assertEquals((-1), int1);
      assertTrue(int1 == int0);
      
      pL_Interface_impl0.Specification3();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification3();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      pL_Interface_impl0.Specification14();
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      
      boolean boolean2 = PL_Interface_impl.getBoolean();
      assertFalse(boolean2);
      assertTrue(boolean2 == boolean0);
      assertTrue(boolean2 == boolean1);
      
      String string0 = PL_Interface_impl.listToString(list0);
      assertFalse(list0.contains(string0));
      assertEquals(" StartFromTop StartFromTop StartFromTop monicaCall monicaCall bigMacCall 1TS", string0);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(list0.isEmpty());
      assertEquals(7, list0.size());
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      pL_Interface_impl0.Specification2();
      int int0 = (-3487);
      PL_Interface_impl.getBoolean();
      pL_Interface_impl0.modifiedrandomSequenceOfActions((-3487));
      pL_Interface_impl0.Specification1();
      pL_Interface_impl0.Specification13();
      pL_Interface_impl0.test((-3487), (-3487));
      pL_Interface_impl0.Specification13();
      pL_Interface_impl0.isAbortedRun();
      pL_Interface_impl0.getExecutedActions();
      PL_Interface_impl.getIntegerMinMax(0, 1120);
      PL_Interface_impl.getBoolean();
      pL_Interface_impl0.Specification13();
      PL_Interface_impl.getIntegerMinMax((-3487), 0);
      int int1 = 1505;
      pL_Interface_impl0.start(1505, 159);
  }
}
